server:
  port: 8082

spring:
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 10s
      lettuce:
        pool:
          max-active: 200
          max-idle: 20
          min-idle: 5
          max-wait: 3000ms
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:qiyu-db-sharding.yaml
  application:
    name: qiyu-live-user-provider
  cloud:
    nacos:
      username: qiyu
      password: qiyu
      server-addr: 127.0.0.1:8848
      discovery:
        namespace: qiyu-live-test
        enabled: true
        register-enabled: true

dubbo:
  application:
    name: qiyu-live-user-application
    qos-enable: false
  registry:
    address: nacos://127.0.0.1:8848?namespace=qiyu-live-test&username=qiyu&password=qiyu
  protocol:
    name: dubbo
    port: 9090
  provider:
    timeout: 3000
  scan:
    base-packages: org.qiyu.live.user.provider.rpc

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: org.qiyu.live.user.provider.dao.po

logging:
  level:
    root: info
    org.qiyu: debug
    org.apache.shardingsphere: info

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: cache-delete-producer-group
    send-message-timeout: 3000
    retry-times-when-send-failed: 2
