dubbo.application.name=qiyu-live-api
dubbo.registry.address=nacos://${NACOS_SERVER_ADDR:127.0.0.1:8848}?namespace=${NACOS_NAMESPACE:qiyu-live-test}&username=${NACOS_USERNAME:qiyu}&password=${NACOS_PASSWORD:qiyu}
dubbo.client.timeout=3000
